### ISSUE TITLE
Deleting package file just after file is downloaded is throwing `The process cannot access the file  because it is being used by another process.

### ISSUE THREAD

**Issue by Morasiu** [bezzad/Downloader#51]
Version 2.2.8

I'm trying to delete the package after the file download is completed and I get an exception
![image](https://user-images.githubusercontent.com/19236279/113320863-4a96f180-9313-11eb-9858-2c1b2ec63a27.png)

My delete method:
```csharp
public static void Delete(this DownloadPackage package, string episodePath) {
	var formattedPath = GetFilePath(episodePath);
	if (!File.Exists(formattedPath)) return;
	File.Delete(formattedPath);
}
```

Message
```
The process cannot access the file 'D:\Download\Kawaii\1.package' because it is being used by another process.
```

File `1.package` is `DownloaderPackage` saved to file using `BinarryFormatter`.

```csharp
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at DownloaderLibrary.Helpers.DownloadPackageExtensions.SavePackage(DownloadPackage package, String episodePath) in D:\Projekty\AnimeVideoDownloader\AnimeVideoDownloader\DownloaderLibrary\Helpers\DownloadPackageExtensions.cs:line 23
   at DownloaderLibrary.Downloaders.BaseAnimeDownloader.<>c__DisplayClass13_0.<DownloadEpisode>b__0(Object sender, DownloadProgressChangedEventArgs args) in D:\Projekty\AnimeVideoDownloader\AnimeVideoDownloader\DownloaderLibrary\Downloaders\BaseAnimeDownloader.cs:line 128
   at Downloader.DownloadService.OnChunkDownloadProgressChanged(Object sender, DownloadProgressChangedEventArgs e)
   at Downloader.ChunkDownloader.OnDownloadProgressChanged(DownloadProgressChangedEventArgs e)
   at Downloader.ChunkDownloader.ReadStream(Stream stream, CancellationToken token)
   at Downloader.ChunkDownloader.DownloadChunk(Request downloadRequest, CancellationToken token)
   at Downloader.ChunkDownloader.Download(Request downloadRequest, CancellationToken cancellationToken)
   at Downloader.ChunkDownloader.Download(Request downloadRequest, CancellationToken cancellationToken)
   at Downloader.DownloadService.SerialDownload(CancellationToken cancellationToken)
   at Downloader.DownloadService.StartDownload()
```
The exception is thrown here.

![image](https://user-images.githubusercontent.com/19236279/113321065-829e3480-9313-11eb-9fe8-7c87caed698d.png)

Why `Downloader` is trying to access the file after the download is completed? How can I safely delete the package after the download is completed?

**Comment by bezzad** [comment]
The downloader service has never taken the address of the package file that it is currently using. The downloader only needs the package object to continue downloading, which you serialized to binary or Json and deserialized from and this has nothing to do with my library because I only use the object from you. Check your application to make sure you have disposed of the stream reader.

**Comment by Morasiu** [comment]
Oh... My bad. Yeah I should Dispose fileInfo. Thanks!
